name: bioinformatics-app
dependencies:
  - pip
  #Buradan aşağısı al
  # - rdkit
  - conda-forge
  - seaborn
  - scipy
  - neatbio
  - pip:
    - pgcontents
    - git+git://github.com/ipython-contrib/jupyter_contrib_nbextensions.git