name: bioinformatics-app
dependencies:
  #Buradan aşağısı al
  - rdkit
  - seaborn
  - scipy
  - neatbio
  - pip:
    - pgcontents
    - git+git://github.com/ipython-contrib/jupyter_contrib_nbextensions.git